### ISSUE TITLE
Field ids for non-sequential IDs in .proto messages

### ISSUE THREAD

**Issue by ghost** [dogtopus/minipb#10]
Hello,
Thank you for this great compact tool.
I am not sure if this is a substantial problem but wanted to get feedback and bring it up. This may be just as much as protocol buffers question as a minipb library issue. I am trying to write a schema that can [decode GTFS Realtime .proto](https://developers.google.com/transit/gtfs-realtime/gtfs-realtime-proto). I am running into decode issues (unexpected end of message for field X) and wondering if it has to do with the field ids issue as described below.

From what I understand, when creating embedded messages or any key-value schema, this library gives them field IDs in sequence. For example, for the following .proto message:

```
message SearchRequest {
  string query = 1; 
  int32 page_number = 2;
  int32 result_per_page = 3;
  enum Corpus {
    UNIVERSAL = 0;
    WEB = 1;
    IMAGES = 2;
    LOCAL = 3;
    NEWS = 4;
    PRODUCTS = 5;
    VIDEO = 6;
  }
  Corpus corpus = 4;
}
```
Results in the following minipb schema:
```
search_req_schema = minipb.Wire((
    ('query', 'U'), # field id 1
    ('page_number', 't'), # field id 2
    ('result_per_page', 't'), # field id 3
    ('corpus', 't'), # field id 4
))
```

For the GTFS realtime .proto there is one Alert message that lists fields in non-sequential number order.

```
// An alert, indicating some sort of incident in the public transit network.
message Alert {
  // Time when the alert should be shown to the user. If missing, the
  // alert will be shown as long as it appears in the feed.
  // If multiple ranges are given, the alert will be shown during all of them.
  repeated TimeRange active_period = 1;

  // Entities whose users we should notify of this alert.
  repeated EntitySelector informed_entity = 5; # *********************SKIPS TO 5 FROM 1**

  // Cause of this alert.
  enum Cause {
    UNKNOWN_CAUSE = 1;
    OTHER_CAUSE = 2;  // Not machine-representable.
    TECHNICAL_PROBLEM = 3;
    STRIKE = 4;         // Public transit agency employees stopped working.
    DEMONSTRATION = 5;  // People are blocking the streets.
    ACCIDENT = 6;
    HOLIDAY = 7;
    WEATHER = 8;
    MAINTENANCE = 9;
    CONSTRUCTION = 10;
    POLICE_ACTIVITY = 11;
    MEDICAL_EMERGENCY = 12;
  }
  optional Cause cause = 6 [default = UNKNOWN_CAUSE];

  // What is the effect of this problem on the affected entity.
  enum Effect {
    NO_SERVICE = 1;
    REDUCED_SERVICE = 2;

    // We don't care about INsignificant delays: they are hard to detect, have
    // little impact on the user, and would clutter the results as they are too
    // frequent.
    SIGNIFICANT_DELAYS = 3;

    DETOUR = 4;
    ADDITIONAL_SERVICE = 5;
    MODIFIED_SERVICE = 6;
    OTHER_EFFECT = 7;
    UNKNOWN_EFFECT = 8;
    STOP_MOVED = 9;
  }
  optional Effect effect = 7 [default = UNKNOWN_EFFECT];

  // The URL which provides additional information about the alert.
  optional TranslatedString url = 8;  

  // Alert header. Contains a short summary of the alert text as plain-text.
  optional TranslatedString header_text = 10;  # ***************** SKIPS TO 10 FROM 8

  // Full description for the alert as plain-text. The information in the
  // description should add to the information of the header.
  optional TranslatedString description_text = 11; 

  // The extensions namespace allows 3rd-party developers to extend the
  // GTFS Realtime Specification in order to add and evaluate new features
  // and modifications to the spec.
  extensions 1000 to 1999;
}
```
I don't know why GTFS realtime proto skip field numbers like this. When converting this to a minipb schema, could that be an issue for properly receiving and decoding messages?

**Comment by dogtopus** [comment]
Some protocols skip fields like this to ensure compatibility and make code and message more readable (namespacing by using prefix numbers). In minipb you can use the `x` type to insert field paddings to the protocol (e.g. `V5x995V`, the last `V` will be field # 1001)

(That being said, the initial purpose of `x` is for skipping occasional reserved fields, and use it for namespacing can become ugly. So for future improvements, it might be nicer to have a dedicated pseudo-type for namespace although I'm not very sure how doable that would be considering I haven't been working with this codebase for a LONG time.)

**Comment by ghost** [comment]
Thank you.
I found my issue by the way.  It was this single field embedded message TranslatedString from gtfs .proto. I didn't properly write the schema.
```
message TranslatedString {
  message Translation {
    // A UTF-8 string containing the message.
    required string text = 1;
    // BCP-47 language code. Can be omitted if the language is unknown or if
    // no i18n is done at all for the feed. At most one translation is
    // allowed to have an unspecified language tag.
    optional string language = 2;

    // The extensions namespace allows 3rd-party developers to extend the
    // GTFS Realtime Specification in order to add and evaluate new features and
    // modifications to the spec.
    extensions 1000 to 1999;
  }
  // At least one translation must be provided.
  repeated Translation translation = 1;

  // The extensions namespace allows 3rd-party developers to extend the
  // GTFS Realtime Specification in order to add and evaluate new features and
  // modifications to the spec.
  extensions 1000 to 1999;
}
```

Forgot to add a comma after this single embedded message so the tuple didn't get nested, and it didn't call _parse_kvfmt correctly in line 166. Lessons were learned about tuple syntax.
```
TranslatedString = (
    ('translation', '+[', Translation,)
)

**Comment by dogtopus** [comment]
For anyone who might be reading this: There's now a feature called [field seek](https://github.com/dogtopus/minipb/wiki/Schema-Representations#suffixes) that allows one to specify field ID and reset the internal field ID counter (i.e. subsequent fields will continue from the set field ID) for a specific field. The old `x` method still works although on sparse schemas it gets ugly really fast so I wouldn't recommend using it.
