### ISSUE TITLE
Oneof

### ISSUE THREAD

**Issue by FlapKap** [dogtopus/minipb#15]
How would you implement `[oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof)` here? as a `required` tag, and then a bunch of optional fields for each possible type? Would that correspond to the `oneof` keyword used in `.proto`?

**Comment by dogtopus** [comment]
I don't think you need required here. Looks like just a bunch of optionals will be fine. Then of course make sure only 1 field is set.

**Comment by FlapKap** [comment]
Oh, right, and then just read the first (and only) non-none value. Thanks!
