### ISSUE TITLE
This is awesome but the docs could be improved

### ISSUE THREAD

**Issue by peterhinch** [dogtopus/minipb#3]
A few usage examples of the `Wire` class in the main README would help greatly, and would help promote adoption of this library.

I'm puzzled that your example in `doc/format_str` uses the `t` type which it explicitly deprecates. If there is a reason to use this, it would be helpful if it were clarified.

I have run this on a Pyboard 1.1 and it works fine, using 13KiB of RAM. Encoding is efficient provided you understand the meaning of the format types - again some explanation may help those unfamiliar with serialisation especially the handling of negative integers. Efficiency is comparable to `ustruct` but it's much more usable.

**Comment by dogtopus** [comment]
`t` is not deprecated. It's just not that efficient (space and potentially performance-wise) compared to other encoding method (i.e. `z` for signed integer and `T` for unsigned). However the only example in format_str was copied from official protobof example and they used int32 which has implicit sign and translates to `t`.

I agree with you that more examples are desireable. Also I will likely do a reformatting on the docs (both pydoc and format string docs) to make it more presentable and also add more information like difference between this and Google Protobuf (yes there are some).

**Comment by peterhinch** [comment]
>  `t` is not deprecated.

Well the doc states `(NOT recommended)` which is quite strong. I had figured out the reason; others might not. I guess there may be reasons for preferring an `int32` in a cross-language application. The `z` encoding is very neat - for a moment I thought "why have Google uninvented two's compliment" and then light dawned :1st_place_medal: 

> I agree with you that more examples are desirable.

When I read docs I find examples which can be cut and pasted at the MicroPython REPL to be hugely encouraging. I wonder if the CPython boys will ever grasp the sheer excellence of ctrl-e...

> like difference between this and Google Protobuf

These definitely need documenting if people are to use it in cross-language applications.

My own applications are for communication between MicroPython hosts so it only needs to be self-consistent. Currently I use `ujson`, `pickle` or `ustruct`. The first two are profligate with bandwidth (but self-describing). The latter is inflexible and not particularly easy to use.

As far as I'm aware you've written the first efficient serialisation library for MicroPython so I'm very enthusiastic about it :+1:

**Comment by dogtopus** [comment]
>Well the doc states (NOT recommended) which is quite strong.

Yeah I figured. The docs and the whole library in general was for another private project that runs on not-so-constrainted-but-still-embedded platform. Some parts might be vague and not polished enough. That's why I'm planning to improve it in the future.

>As far as I'm aware you've written the first efficient serialisation library for MicroPython

Thanks. Never thought this would mean so much to MicroPython.

**Comment by pepijndevos** [comment]
Some docs you might steal: https://github.com/peterhinch/micropython-samples/blob/master/SERIALISATION.md#5-protocol-buffers

One thing that might be worth mentioning explicitly is... a "typical" protobuf example has the field order and field numbers lined up, but I happen to stumble across a case where the first field is lik `required int version = 15` or whatever and it took a bit of puzzling to figure out that means it needs to go at the end with some `x` fields between. Obvious in retrospect, but... worth mentioning if you're just trying to transcribe some existing protobuf thing.

**Comment by dogtopus** [comment]
Closing this now. The documentation still can have some improvement but I'll not track them here.
