### ISSUE TITLE
Recommendation for a separator character?

### ISSUE THREAD

**Issue by peterhinch** [dogtopus/minipb#4]
If a variety of data items are encoded with the same schema, the length of the resultant `bytes` object varies. To send this data down a stream such as a UART the simplest approach is to terminate each object with a separator byte (b'\n'?). But that byte needs to be one guaranteed not to be present in any possible encoding.

Is there such a byte?

**Comment by dogtopus** [comment]
I think the usual way to do this is to include a header that encodes the length of the serialized object. It could just be a simple uint16/32 depends on what you need. I saw some protocols use this approach.

**Comment by peterhinch** [comment]
OK, thank you.
